export const LOGIN_REQUEST = "ISC/LOGIN_REQUEST";
export const LOGIN_SUCCESS = "ISC/LOGIN_SUCCESS";
export const LOGIN_FAILURE = "ISC/LOGIN_FAILURE";

export const LOGOUT_REQUEST = "ISC/LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "ISC/LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "ISC/LOGOUT_FAILURE";
